### ISSUE TITLE
error running `data_structures/binary_tree.py` by hand

### ISSUE THREAD

**Issue by a1eaiactaest** [a1eaiactaest/ads#2]
```
prybiec :: ~/fun/ADS/ads/data_structures 1 » python3 binary_tree.py
Traceback (most recent call last):
  File "/Users/prybiec/fun/ADS/ads/data_structures/binary_tree.py", line 388, in <module>
    x = build_binary_tree([50,None,54,98,6,None,None,None,34])
  File "/Users/prybiec/fun/ADS/ads/data_structures/binary_tree.py", line 366, in build_binary_tree
    root.insert(arr[i])
  File "/Users/prybiec/fun/ADS/ads/data_structures/binary_tree.py", line 105, in insert
    if data < self.data and self.left is not None:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by a1eaiactaest** [comment]
Also write tests for this, if this isn't working and tests are passing something is wrong.
